"use client";

import React from "react";
import { Document, Font, Image, Link, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import { profile } from "@/data/profile";

const isBrowser = typeof window !== "undefined";
const assetBase = isBrowser ? window.location.origin : `${process.cwd()}/public`;
Font.register({ family: "Pretendard", fonts: [{ src: `${assetBase}/fonts/Pretendard-Regular.otf`, fontWeight: 400 }, { src: `${assetBase}/fonts/Pretendard-Bold.otf`, fontWeight: 700 }] });
Font.registerHyphenationCallback((word) => [word]);

const image = (path: string) => isBrowser ? `${assetBase}/images-pdf/${encodeURI(path)}` : `${assetBase}/images-pdf/${path}`;

const styles = StyleSheet.create({
  page: { paddingTop: 40, paddingBottom: 38, paddingHorizontal: 42, fontFamily: "Pretendard", fontSize: 8.9, lineHeight: 1.6, color: "#334155", backgroundColor: "#FFFFFF" },
  cover: { padding: 54, fontFamily: "Pretendard", backgroundColor: "#0F172A", color: "#FFFFFF" },
  coverEyebrow: { fontSize: 9, color: "#67E8F9", marginBottom: 18 },
  coverName: { fontSize: 34, fontWeight: 700, lineHeight: 1.15, marginBottom: 8 },
  coverRole: { fontSize: 15, color: "#CBD5E1", marginBottom: 28, lineHeight: 1.35 },
  coverStatement: { fontSize: 19, fontWeight: 700, lineHeight: 1.5, maxWidth: 390, marginBottom: 22 },
  coverSummary: { fontSize: 10.2, lineHeight: 1.78, color: "#CBD5E1", maxWidth: 390 },
  coverBottom: { position: "absolute", left: 54, right: 54, bottom: 48, flexDirection: "row", justifyContent: "space-between", alignItems: "flex-end", paddingTop: 16, borderTop: "1px solid #334155" },
  coverContact: { fontSize: 8.2, color: "#94A3B8", lineHeight: 1.7 },
  header: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 20 },
  headerName: { fontSize: 9, fontWeight: 700, color: "#0F172A" },
  headerRole: { fontSize: 7.2, color: "#0891B2", marginTop: 2 },
  headerSection: { fontSize: 7.2, color: "#94A3B8", textAlign: "right" },
  eyebrow: { fontSize: 7.5, fontWeight: 700, color: "#0891B2", marginBottom: 7 },
  title: { fontSize: 20, fontWeight: 700, color: "#0F172A", lineHeight: 1.28, marginBottom: 10 },
  intro: { fontSize: 9.4, color: "#64748B", lineHeight: 1.72, marginBottom: 18, maxWidth: 475 },
  sectionTitle: { fontSize: 12.5, fontWeight: 700, color: "#0F172A", paddingBottom: 5, borderBottom: "1px solid #CBD5E1", marginBottom: 9 },
  grid: { flexDirection: "row", flexWrap: "wrap", gap: 9 },
  capability: { width: "48.9%", minHeight: 80, padding: 11, backgroundColor: "#F8FAFC", borderTop: "2px solid #0F172A", borderRadius: 3 },
  cardTitle: { fontSize: 10, fontWeight: 700, color: "#0F172A", marginBottom: 5, lineHeight: 1.35 },
  cardText: { fontSize: 8.05, color: "#475569", lineHeight: 1.62 },
  workCard: { width: "32.1%", minHeight: 116, padding: 11, backgroundColor: "#F1F5F9", borderRadius: 4 },
  workNumber: { fontSize: 7.2, color: "#0891B2", marginBottom: 7 },
  workMeta: { fontSize: 7.1, color: "#64748B", marginBottom: 5 },
  resultRow: { flexDirection: "row", gap: 8, marginBottom: 16 },
  resultCard: { flex: 1, padding: 11, backgroundColor: "#ECFEFF", borderTop: "3px solid #0891B2", borderRadius: 3 },
  resultValue: { fontSize: 15, fontWeight: 700, color: "#0E7490", lineHeight: 1.2 },
  resultLabel: { fontSize: 7.4, color: "#475569", marginTop: 4, lineHeight: 1.4 },
  caseGrid: { flexDirection: "row", gap: 14 },
  caseCol: { flex: 1 },
  label: { fontSize: 7.4, fontWeight: 700, color: "#0F172A", marginBottom: 5, lineHeight: 1.35 },
  body: { fontSize: 8.2, color: "#475569", lineHeight: 1.65 },
  bullet: { fontSize: 8.05, color: "#475569", lineHeight: 1.6, marginBottom: 3.2 },
  quote: { marginTop: 12, padding: 11, backgroundColor: "#F8FAFC", borderLeft: "3px solid #0891B2", fontSize: 8.4, color: "#334155", lineHeight: 1.66 },
  flow: { flexDirection: "row", alignItems: "center", gap: 5, marginTop: 9 },
  flowBox: { flex: 1, minHeight: 47, padding: 8, backgroundColor: "#F1F5F9", borderRadius: 3, justifyContent: "center" },
  flowTitle: { fontSize: 7.6, fontWeight: 700, color: "#0F172A", textAlign: "center", marginBottom: 2 },
  flowText: { fontSize: 6.6, color: "#64748B", textAlign: "center", lineHeight: 1.35 },
  arrow: { fontSize: 10, color: "#0891B2" },
  imageRow: { flexDirection: "row", gap: 8, marginTop: 13 },
  screenImage: { flex: 1, height: 190, objectFit: "contain", backgroundColor: "#F8FAFC", borderRadius: 4 },
  wideImage: { width: "100%", height: 214, objectFit: "contain", backgroundColor: "#F8FAFC", borderRadius: 4, marginTop: 13 },
  imageCaption: { fontSize: 7, color: "#94A3B8", marginTop: 6, textAlign: "center", lineHeight: 1.4 },
  projectCard: { width: "48.9%", padding: 12, backgroundColor: "#F8FAFC", borderTop: "2px solid #0F172A", borderRadius: 3 },
  projectMeta: { fontSize: 7.2, color: "#0891B2", marginBottom: 5 },
  projectImage: { width: "100%", height: 118, objectFit: "contain", backgroundColor: "#FFFFFF", borderRadius: 3, marginBottom: 8 },
  tags: { fontSize: 7, color: "#64748B", marginTop: 7, lineHeight: 1.5 },
  timeline: { flexDirection: "row", marginBottom: 8 },
  timelinePeriod: { width: 105, fontSize: 7.6, color: "#64748B" },
  timelineCompany: { width: 110, fontSize: 8.5, fontWeight: 700, color: "#0F172A" },
  timelineRole: { flex: 1, fontSize: 7.8, color: "#475569" },
  link: { color: "#0E7490", textDecoration: "none" },
  footer: { position: "absolute", left: 42, right: 42, bottom: 18, flexDirection: "row", justifyContent: "space-between", fontSize: 7, color: "#94A3B8" },
});

type Language = "ko" | "en";

const ko = {
  statement: "복잡한 문제와 아이디어를\n실제로 운영되는 제품으로 만듭니다.",
  summary: "모바일을 주력으로 백엔드, 배포·운영, 현장 시스템과 AI 워크플로를 연결하고, 불명확한 문제를 실제 사용되는 제품으로 만드는 Product Engineer입니다.",
  capabilities: [["모바일 제품 오너십", "Flutter iOS·Android 앱의 구조, 기능, 배포와 운영 품질을 제품 단위로 책임집니다."], ["0→1 제품화와 확장", "고객과 제품이 없는 단계에서 첫 버전을 만들고 실제 도입과 장기 운영까지 이어갑니다."], ["제품 경계를 넘는 실행", "모바일에서 끝내지 않고 웹·백엔드·인프라·결제·현장 장비를 필요한 만큼 연결합니다."], ["AI/AX 워크플로 전환", "기존 업무와 판단 지점을 분석해 AI가 보조·자동화하는 운영 흐름으로 재설계합니다."]],
  selected: [["01", "헤이링 AI", "현재 제품", "빌드 71% 단축, 일본어 학습, 예약 전화 인프라 개선 설계"], ["02", "잇츠미·잇츠밀", "성장 사례", "0→1 출시에서 13개 대학 운영과 흑자 전환까지"], ["03", "한국외대 AI 챗봇", "AI/AX 사례", "근거 기반 학사 안내, DAU 약 80명·하루 질문 약 300건"]],
};

const en = {
  statement: "I turn complex problems and ideas\ninto products that actually operate.",
  summary: "A Product Engineer specializing in mobile while connecting backend, delivery, field systems, and AI workflows to turn ambiguous problems into products people actually use.",
  capabilities: [["Own the mobile product", "Own Flutter iOS and Android architecture, features, delivery, and operational quality as one product."], ["Build zero-to-one and scale", "Create the first usable version before customers exist and carry it into adoption and long-term operations."], ["Execute across product boundaries", "Extend beyond mobile into web, backend, infrastructure, payments, and field hardware when the problem requires it."], ["Transform workflows with AI", "Map existing work and decision points, then redesign them into AI-assisted and automated operations."]],
  selected: [["01", "Heyring AI", "Current product", "71% faster builds, Japanese learning, scheduled-call architecture design"], ["02", "ItsMe · ItsMeal", "Growth case", "From zero-to-one launch to 13 universities and profitability"], ["03", "HUFS AI Chatbot", "AI/AX case", "Grounded academic answers, about 80 DAU and 300 daily questions"]],
};

function Header({ section, language }: { section: string; language: Language }) { return <View style={styles.header}><View><Text style={styles.headerName}>{profile.name[language]}</Text><Text style={styles.headerRole}>{profile.title[language]}</Text></View><Text style={styles.headerSection}>{section}</Text></View>; }
function Footer() { return <View style={styles.footer} fixed><Text>박태준 · Portfolio</Text><Text render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} /></View>; }
function Heading({ eyebrow, title, intro }: { eyebrow: string; title: string; intro: string }) { return <><Text style={styles.eyebrow}>{eyebrow}</Text><Text style={styles.title}>{title}</Text><Text style={styles.intro}>{intro}</Text></>; }
function Results({ items }: { items: string[][] }) { return <View style={styles.resultRow}>{items.map(([value, label]) => <View key={label} style={styles.resultCard}><Text style={styles.resultValue}>{value}</Text><Text style={styles.resultLabel}>{label}</Text></View>)}</View>; }
function ProjectCard({ title, meta, description, tags, src }: { title: string; meta: string; description: string; tags: string; src?: string }) { return <View style={styles.projectCard} wrap={false}>{src ? <Image style={styles.projectImage} src={image(src)}/> : null}<Text style={styles.cardTitle}>{title}</Text><Text style={styles.projectMeta}>{meta}</Text><Text style={styles.cardText}>{description}</Text><Text style={styles.tags}>{tags}</Text></View>; }

export default function PortfolioDocument({ language }: { language: Language }) {
  const isKo = language === "ko";
  const t = isKo ? ko : en;
  return <Document title={`${profile.name[language]} - Portfolio`} author={profile.name[language]}>
    <Page size="A4" style={styles.cover}><Text style={styles.coverEyebrow}>PRODUCT ENGINEER · MOBILE SYSTEMS · AI/AX</Text><Text style={styles.coverName}>{profile.name[language]}</Text><Text style={styles.coverRole}>Product Engineer · Mobile Systems · AI/AX</Text><Text style={styles.coverStatement}>{t.statement}</Text><Text style={styles.coverSummary}>{t.summary}</Text><View style={styles.coverBottom}><View><Text style={styles.coverContact}>{profile.email}</Text><Text style={styles.coverContact}>{profile.phone}</Text></View><View><Text style={[styles.coverContact, { textAlign: "right" }]}>puze8681.github.io</Text><Text style={[styles.coverContact, { textAlign: "right" }]}>github.com/puze8681</Text></View></View></Page>

    <Page size="A4" style={styles.page}><Header section={isKo ? "소개 · 핵심 역량" : "PROFILE · CAPABILITIES"} language={language}/><Heading eyebrow="01 · PROFILE" title={isKo ? "모바일을 중심으로 제품 전체를 소유합니다" : "Owning the Whole Product from a Mobile Core"} intro={t.summary}/><View style={styles.grid}>{t.capabilities.map(([title, text]) => <View key={title} style={styles.capability} wrap={false}><Text style={styles.cardTitle}>{title}</Text><Text style={styles.cardText}>{text}</Text></View>)}</View><Text style={[styles.sectionTitle, { marginTop: 18 }]}>{isKo ? "대표 사례" : "Selected Case Studies"}</Text><View style={styles.grid}>{t.selected.map(([number, title, meta, text]) => <View key={number} style={styles.workCard} wrap={false}><Text style={styles.workNumber}>{number}</Text><Text style={styles.cardTitle}>{title}</Text><Text style={styles.workMeta}>{meta}</Text><Text style={styles.cardText}>{text}</Text></View>)}</View><Footer/></Page>

    <Page size="A4" style={styles.page}><Header section={isKo ? "대표 작업 01 · 헤이링 AI" : "SELECTED WORK 01 · HEYRING AI"} language={language}/><Heading eyebrow={isKo ? "현재 제품 · 2026.07 - 현재" : "CURRENT PRODUCT · 2026.07 - PRESENT"} title={isKo ? "헤이링(Heyring) AI" : "Heyring AI"} intro={isKo ? "AI 튜터와의 예약 통화와 맞춤 피드백을 제공하는 언어 학습 제품에서 모바일 앱, 학습 기능, 배포 파이프라인과 예약 전화 인프라 개선 설계를 담당합니다." : "An AI phone-based language-learning product where I work across mobile, learning features, delivery, and scheduled-call infrastructure improvement design."}/><Results items={isKo ? [["21분 → 6분", "모바일 빌드 시간"], ["약 71%", "빌드 대기 시간 단축"], ["영어 + 일본어", "지원 학습 언어"]] : [["21m → 6m", "Mobile build time"], ["About 71%", "Build wait reduction"], ["English + Japanese", "Learning languages"]]}/><View style={styles.caseGrid}><View style={styles.caseCol}><Text style={styles.label}>{isKo ? "문제와 역할" : "Problem and Role"}</Text><Text style={styles.body}>{isKo ? "입사 직후 긴 모바일 빌드 과정과 영어 중심 학습 경험을 개선했습니다. 전화 발송은 API와 같은 EC2에서 처리해 커넥션 한도 때문에 예약 발송이 지연되는 문제가 있었습니다." : "Improved a long mobile build process and an English-only learning experience. Scheduled delivery shared one EC2 instance with the API and hit connection limits."}</Text></View><View style={styles.caseCol}><Text style={styles.label}>{isKo ? "주요 실행" : "Key Actions"}</Text>{(isKo ? ["모바일 CI/CD 적용과 빌드 병목 개선", "일본어 학습과 단어·표현 저장·복습 기능", "예약 발송 책임을 단계별로 나눈 개선 구조 설계"] : ["Introduced mobile CI/CD and removed build bottlenecks", "Added Japanese and save-and-review learning", "Designed responsibility separation for scheduled delivery"]).map((x) => <Text key={x} style={styles.bullet}>• {x}</Text>)}</View></View><Text style={styles.sectionTitle}>{isKo ? "예약 전화 개선 설계" : "Scheduled-call Improvement Design"}</Text><View style={styles.flow}>{(isKo ? [["Scheduler", "1분 주기 대상 생성"], ["Dispatcher", "발송 조건 판단"], ["Queue", "비동기 작업 완충"], ["Worker", "실제 발송 처리"]] : [["Scheduler", "Create due work"], ["Dispatcher", "Evaluate delivery"], ["Queue", "Buffer async work"], ["Worker", "Execute delivery"]]).map(([a,b], i, arr) => <React.Fragment key={a}><View style={styles.flowBox}><Text style={styles.flowTitle}>{a}</Text><Text style={styles.flowText}>{b}</Text></View>{i < arr.length - 1 ? <Text style={styles.arrow}>›</Text> : null}</React.Fragment>)}</View><Text style={styles.quote}>{isKo ? "구현 완료 효과가 아니라, 단일 서버 병목과 장애 전파를 줄이기 위해 역할별 책임과 적합한 관리형 제품 조합을 설계한 작업입니다." : "This is an infrastructure improvement design: responsibility boundaries and managed-product choices intended to reduce bottlenecks and failure propagation."}</Text><Footer/></Page>

    <Page size="A4" style={styles.page}><Header section={isKo ? "대표 작업 02 · 잇츠미·잇츠밀" : "SELECTED WORK 02 · ITSME & ITSMEAL"} language={language}/><Heading eyebrow="ZERO TO ONE · SCALE · OPERATIONS" title={isKo ? "잇츠미·잇츠밀을 하나의 성장 사례로" : "ItsMe and ItsMeal as One Growth Story"} intro={isKo ? "고객사와 매출, 운영 서비스가 없던 시점에 합류해 첫 제품을 출시하고, 예정에 없던 매장 운영 제품을 새로 만들어 13개 대학 운영과 흑자 전환 시점까지 함께했습니다." : "Joined before a live service, customer, or revenue existed; launched the first product, created an unplanned store-operations product, and owned core development through 13 universities and profitability."}/><Results items={isKo ? [["2개월", "잇츠미 첫 버전 출시"], ["13개", "두 제품 통합 도입 대학"], ["사업 흑자 전환", "전환 시점까지 제품 개발·운영"]] : [["2 months", "ItsMe first launch"], ["13", "Universities combined"], ["Profitability", "Product development and operations"]]}/><View style={styles.caseGrid}><View style={styles.caseCol}><Text style={styles.label}>{isKo ? "잇츠미" : "ItsMe"}</Text><Text style={styles.body}>{isKo ? "입사 후 2개월 동안 Flutter 앱의 구조와 핵심 기능을 구현해 출시하고 한국외대를 첫 고객으로 연결했습니다. 대학별 요구사항을 공통 제품 구조로 흡수하며 장기 운영했습니다." : "Built and launched the Flutter app in two months, enabling HUFS as the first customer. Absorbed university-specific needs into a shared product over long-term operations."}</Text></View><View style={styles.caseCol}><Text style={styles.label}>{isKo ? "잇츠밀" : "ItsMeal"}</Text><Text style={styles.body}>{isKo ? "외부 POS·키오스크 연동보다 직접 만드는 편이 낫다고 판단해, 예정에 없던 POS·키오스크·KDS·매장 운영 제품을 0→1로 설계하고 개발했습니다." : "Concluded that an in-house system was better than external POS/kiosk integration and designed the unplanned POS, kiosk, KDS, and store-operations product from zero."}</Text></View></View><View style={styles.imageRow}><Image style={styles.screenImage} src={image("itsme/itsme1.png")}/><Image style={styles.screenImage} src={image("itsmeal/kiosk1.png")}/><Image style={styles.screenImage} src={image("itsmeal/pos1.png")}/></View><Text style={styles.imageCaption}>{isKo ? "잇츠미 모바일 · 잇츠밀 키오스크 · 잇츠밀 POS" : "ItsMe mobile · ItsMeal kiosk · ItsMeal POS"}</Text><Footer/></Page>

    <Page size="A4" style={styles.page}><Header section={isKo ? "대표 작업 02 · 현장 시스템과 접근성" : "SELECTED WORK 02 · SYSTEMS & ACCESSIBILITY"} language={language}/><Heading eyebrow="FIELD SYSTEMS · ACCESSIBILITY" title={isKo ? "100+ 매장과 300+ 기기를 운영하는 시스템" : "Systems Operating Across 100+ Stores and 300+ Devices"} intro={isKo ? "모바일 앱 하나가 아니라 결제·상품·주문·주방·호출·매출·키오스크와 외부 장비를 하나의 현장 운영 흐름으로 연결했습니다." : "Connected payments, catalog, orders, kitchen display, pagers, sales, kiosks, and external hardware into one field-operations flow."}/><Results items={isKo ? [["100+", "도입 매장"], ["300+", "설치 기기"], ["NIA", "베리어프리 검증 통과"]] : [["100+", "Stores"], ["300+", "Installed devices"], ["NIA", "Accessibility verified"]]}/><View style={styles.caseGrid}><View style={styles.caseCol}><Text style={styles.label}>{isKo ? "하드웨어와 결제" : "Hardware and Payments"}</Text>{(isKo ? ["ANDNVCAT 및 WVCAT 계열 결제", "USB·LAN·Bluetooth 프린터", "NFC·바코드 스캐너·FaceSign"] : ["ANDNVCAT and WVCAT-family payments", "USB, LAN, and Bluetooth printers", "NFC, barcode scanners, and FaceSign"]).map((x) => <Text key={x} style={styles.bullet}>• {x}</Text>)}</View><View style={styles.caseCol}><Text style={styles.label}>{isKo ? "베리어프리 키오스크" : "Barrier-free Kiosk"}</Text>{(isKo ? ["TTS·포커스·단계별 음성 안내", "고대비·확대·낮은 자세 모드", "시험평가기관 대응과 검증서 발급"] : ["TTS, focus, and step guidance", "High contrast, zoom, and low-position mode", "Testing response and certification"]).map((x) => <Text key={x} style={styles.bullet}>• {x}</Text>)}</View></View><View style={styles.imageRow}><Image style={styles.screenImage} src={image("itsmeal/kiosk2.png")}/><Image style={styles.screenImage} src={image("itsmeal/kiosk3.png")}/><Image style={styles.screenImage} src={image("itsmeal/kiosk4.png")}/></View><Text style={styles.quote}>{isKo ? "실제 도입 규모와 현장 운영, 접근성 검증, 사업 성장이 이 프로젝트의 성과를 보여줍니다." : "Deployment scale, field operations, accessibility verification, and business growth demonstrate the project's impact."}</Text><Footer/></Page>

    <Page size="A4" style={styles.page}><Header section={isKo ? "대표 작업 03 · 한국외대 AI 챗봇" : "SELECTED WORK 03 · HUFS AI CHATBOT"} language={language}/><Heading eyebrow="AI · RAG · EDUCATION AX" title={isKo ? "한국외대 AI 학사 챗봇" : "HUFS AI Academic Chatbot"} intro={isKo ? "전자규정집과 학사 데이터를 기반으로 답변하고 근거 조항을 함께 제시하는 교육 AX PoC입니다. 검증된 Q&A와 구조적 RAG를 결합하고, 회귀 테스트로 품질을 관리합니다." : "An education AX PoC answering from regulations and academic data with source citations. Combines verified Q&A with structural RAG and manages quality through regression tests."}/><Results items={isKo ? [["약 80명", "오픈 2주차 DAU"], ["약 300건", "하루 질문 수"], ["진행 중", "2026.08 개발 · 09 PoC"]] : [["About 80", "DAU in week two"], ["About 300", "Daily questions"], ["Ongoing", "Built Aug · PoC Sep 2026"]]}/><View style={styles.caseGrid}><View style={styles.caseCol}><Text style={styles.label}>{isKo ? "핵심 설계" : "Core Design"}</Text>{(isKo ? ["검증 Q&A와 구조적 RAG의 하이브리드 답변", "답변별 학칙·규정 근거 조항 인용", "낮은 신뢰도 답변의 검토·승인 흐름"] : ["Hybrid verified Q&A and structural RAG", "Regulation citations attached to answers", "Review and approval for low confidence"]).map((x) => <Text key={x} style={styles.bullet}>• {x}</Text>)}</View><View style={styles.caseCol}><Text style={styles.label}>{isKo ? "품질 운영" : "Quality Operations"}</Text>{(isKo ? ["질의 정규화와 평가 데이터 관리", "회귀 테스트 기반 품질 검증", "실사용 질문을 통한 지속 개선"] : ["Query normalization and evaluation data", "Regression-based quality checks", "Continuous improvement from live questions"]).map((x) => <Text key={x} style={styles.bullet}>• {x}</Text>)}</View></View><Image style={styles.wideImage} src={image("hufs-chatbot/og-image.png")}/><Link style={[styles.body, styles.link, { marginTop: 9 }]} src="https://chat.hufs.ac.kr/">https://chat.hufs.ac.kr/</Link><Footer/></Page>

    <Page size="A4" style={styles.page}><Header section={isKo ? "추가 작업 · DX/AX" : "ADDITIONAL WORK · DX/AX"} language={language}/><Heading eyebrow="ADDITIONAL WORK" title={isKo ? "다른 도메인의 운영 문제를 제품으로" : "Turning More Operational Problems into Products"} intro={isKo ? "대표 사례 외에도 교육, AI 보안기업 운영, 지역 매장 서비스에서 웹·앱·키오스크와 자동화를 연결했습니다." : "Beyond the selected cases, I connected web, mobile, kiosks, and automation across education, AI security operations, and local commerce."}/><View style={styles.grid}><ProjectCard src="thatsone/kiosk-landing.png" title={isKo ? "댓츠원 DX 플랫폼" : "That'sOne DX Platform"} meta={isKo ? "2026.05 - 2026.10 예정" : "2026.05 - planned 2026.10"} description={isKo ? "관리자 웹·학생용 PWA·내부 키오스크를 통합 구축하고 실장 중심 상담의 AI 전환을 진행하고 있습니다." : "Building an integrated admin web app, student PWA, and kiosk while converting consulting into an AI-assisted workflow."} tags="Next.js · Spring Boot · PostgreSQL · PWA · AI"/><ProjectCard title={isKo ? "PintaAI 내부 운영 AX" : "PintaAI Operations AX"} meta={isKo ? "2026.07 - 현재" : "2026.07 - PRESENT"} description={isKo ? "반복 운영 업무의 자동화 설계·구축과 클라우드 운영 전환을 진행하고, 일부 흐름을 단계적으로 운영 환경에 이관하고 있습니다." : "Designing and building automation for recurring operations, moving selected workflows gradually into production."} tags="TypeScript · Node.js · PostgreSQL · Playwright · GCP · LLM"/><ProjectCard src="raintown/raintown-admin1.png" title={isKo ? "레인타운쿠폰" : "Raintown Coupon"} meta={isKo ? "2025.02 - 현재" : "2025.02 - PRESENT"} description={isKo ? "디자인, Flutter 앱, Firebase 백엔드, React 관리자 웹, 배포와 운영을 연결해 실제 서비스를 지속 운영하고 있습니다." : "Operating the live product across design, Flutter, Firebase backend, React admin, delivery, and support."} tags="Flutter · Firebase · React · Next.js"/><ProjectCard src="yunit/yunit1.png" title={isKo ? "윤잇 브랜드 앱" : "Yooneat Brand App"} meta="2025.08 - 2025.11" description={isKo ? "PG 결제, 구독 정기결제, 쿠폰과 푸시를 포함한 커머스 모바일 앱을 개발해 출시했습니다." : "Built and launched a commerce app with PG payments, subscriptions, coupons, and push."} tags="Flutter · Payments · Subscription · FCM"/></View><Footer/></Page>

    <Page size="A4" style={styles.page}><Header section={isKo ? "추가 작업 · 현장 시스템" : "ADDITIONAL WORK · FIELD SYSTEMS"} language={language}/><Heading eyebrow="ADDITIONAL WORK" title={isKo ? "현장에서 검증한 결제·키오스크 경험" : "Payment and Kiosk Work Proven in the Field"} intro={isKo ? "팝업스토어, 골프 대회, 매장, 학원 등 운영 환경이 다른 현장에서 결제와 하드웨어를 안정적으로 연결했습니다." : "Integrated payments and hardware across pop-ups, golf tournaments, stores, and academies with different operational constraints."}/><View style={styles.grid}><ProjectCard src="chzzk/Slide 16_9 - 29.png" title={isKo ? "치지직 팝업스토어 키오스크" : "Chzzk Pop-up Kiosk"} meta="2024.05" description={isKo ? "네이버 FaceSign 얼굴인식 결제와 팝업스토어 현장 주문·결제를 연결했습니다." : "Connected Naver FaceSign with on-site ordering and payment."} tags="Flutter · Kiosk · FaceSign · Payments"/><ProjectCard src="klpga/klpga1.png" title={isKo ? "KLPGA 입장권 키오스크" : "KLPGA Ticket Kiosk"} meta="2025.04 - 2025.08" description={isKo ? "사전 협의된 4개 대회의 티켓 선택, 재고 연동, 결제와 발권 흐름을 개발했습니다." : "Built ticket selection, inventory sync, payment, and issuing for four agreed tournaments."} tags="Flutter · Kiosk · Payments · Ticketing"/><ProjectCard src="chewing/chewing1.png" title={isKo ? "츄잉 결제·출결 앱" : "Chewing Payment & Attendance"} meta="2025.07 - 2025.09" description={isKo ? "Jetpack Compose 앱에 WVCAT 결제, 얼굴인식, 바코드 스캐너를 연동했습니다." : "Integrated WVCAT payments, face recognition, and barcode scanning in a Compose app."} tags="Kotlin · Compose · WVCAT · DeepPass"/><ProjectCard src="bankx/bankx1.png" title="BankX · Windows POS Agent" meta="2025.04 - 2025.08" description={isKo ? "플로팅 모드, USB 영수증 프린터, 결제·환불 내역을 제공하는 Windows 에이전트를 개발했습니다." : "Built a Windows agent with floating mode, USB receipt printing, and payment history."} tags="Flutter Windows · ESC/POS · USB"/></View><Footer/></Page>

    <Page size="A4" style={styles.page}><Header section={isKo ? "경력 · 기술 · 연락처" : "CAREER · SKILLS · CONTACT"} language={language}/><Heading eyebrow="PROFILE" title={isKo ? "제품이 운영되는 지점까지 연결합니다" : "I Connect Work to the Point of Operation"} intro={profile.summary[language]}/><Text style={styles.sectionTitle}>{isKo ? "경력" : "Experience"}</Text>{(isKo ? [["2026.07 - 현재", "하이퍼노바", "Product Engineer"], ["2021.12 - 2026.02", "화이트블록", "Developer"], ["2021.02 - 2021.12", "로플랫", "Software Engineer"], ["2019.12 - 2020.08", "주식회사옷깃", "Android Developer"], ["2019.08 - 2019.10", "에브리웨어", "Android Developer"]] : [["2026.07 - Present", "Hypernova", "Product Engineer"], ["2021.12 - 2026.02", "Whiteblock", "Developer"], ["2021.02 - 2021.12", "Loplat", "Software Engineer"], ["2019.12 - 2020.08", "Otgit", "Android Developer"], ["2019.08 - 2019.10", "Everywear", "Android Developer"]]).map(([period, company, role]) => <View key={company} style={styles.timeline}><Text style={styles.timelinePeriod}>{period}</Text><Text style={styles.timelineCompany}>{company}</Text><Text style={styles.timelineRole}>{role}</Text></View>)}<Text style={[styles.sectionTitle, { marginTop: 14 }]}>{isKo ? "핵심 기술" : "Core Technologies"}</Text><View style={styles.grid}>{[["Mobile", "Flutter · Dart · Kotlin · Swift · React Native"], ["Web & Backend", "React · Next.js · Spring Boot · FastAPI · Node.js · PostgreSQL"], ["AI & Automation", "LLM · RAG · Agentic Workflow · Playwright"], ["Infrastructure & CI/CD", "GCP · Docker · GitHub Actions · Fastlane · Queue Architecture"]].map(([title, text]) => <View key={title} style={styles.capability}><Text style={styles.cardTitle}>{title}</Text><Text style={styles.cardText}>{text}</Text></View>)}</View><Text style={[styles.sectionTitle, { marginTop: 14 }]}>{isKo ? "학력·수료 및 연락처" : "Education, Training, and Contact"}</Text><View style={styles.caseGrid}><View style={styles.caseCol}><Text style={styles.body}>{isKo ? "한국외국어대학교 컴퓨터공학부 · 재학 중\n소프트웨어 마에스트로 9기" : "Hankuk University of Foreign Studies · Computer Science\nSW Maestro 9th"}</Text></View><View style={styles.caseCol}><Text style={styles.body}>{profile.email} · {profile.phone}</Text><Link style={[styles.body, styles.link]} src={profile.portfolio ?? ""}>puze8681.github.io</Link><Link style={[styles.body, styles.link]} src={profile.github}>github.com/puze8681</Link></View></View><Footer/></Page>
  </Document>;
}
